project:
  type: website

website:
  title: "Dr. Hasan Sarıcı"
  navbar:
    left:
      - href: index.qmd
        text: Ana Sayfa
      - href: about.qmd
        text: Hakkımda

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

babelquarto:
  languagelinks: navbar
  languagecodes:
    - name: tr
      text: "TR"
    - name: en
      text: "EN"
  mainlanguage: "tr"
  languages: ["en"]

title-en: "Dr. Hasan Sarıcı"
lang: tr

